### ISSUE TITLE
unit test failures on Moodle 4.5 branch

### ISSUE THREAD

**Issue by danmarsden** [Neuronys/moodle-local_nolej#27]
These prevent us from being able to deploy the plugin to our 4.5 sites - we run continuous integration processes which trigger unit tests prior to code deployment. I might get a chance to send through a PR to fix these, but depends on how much time I have.

thanks!

1) local_nolej\api_test::test_lookupdocument
TypeError: Cannot assign string to property local_nolej\api::$contextid of type int
/builds/elearning/moodle/local/nolej/tests/api_test.php:153
/builds/elearning/moodle/lib/phpunit/classes/advanced_testcase.php:76
2) local_nolej\api_test::test_tokens
TypeError: Cannot assign string to property local_nolej\api::$contextid of type int
/builds/elearning/moodle/local/nolej/tests/api_test.php:182
/builds/elearning/moodle/lib/phpunit/classes/advanced_testcase.php:76
3) local_nolej\external\get_library_updates_test::test_execute
core\exception\coding_exception: Coding error detected, it must be fixed by a programmer: When including this file for a unit test, the test must be run in an isolated process. See the PHPUnit @runInSeparateProcess and @runTestsInSeparateProcesses annotations.
/builds/elearning/moodle/lib/setuplib.php:1711
/builds/elearning/moodle/lib/externallib.php:35
/builds/elearning/moodle/local/nolej/classes/external/get_library_updates.php:29
/builds/elearning/moodle/lib/classes/component.php:217
/builds/elearning/moodle/local/nolej/tests/external/get_library_updates_test.php:102
/builds/elearning/moodle/lib/phpunit/classes/advanced_testcase.php:76
--
There was 1 failure:
1) local_nolej\external\get_library_updates_test::test_capabilities_missing
Failed asserting that exception of type "Error" matches expected exception "required_capability_exception". Message was: "Class "local_nolej\external\get_library_updates" not found" at
/builds/elearning/moodle/local/nolej/tests/external/get_library_updates_test.php:144
/builds/elearning/moodle/lib/phpunit/classes/advanced_testcase.php:76
.
/builds/elearning/moodle/lib/phpunit/classes/advanced_testcase.php:76

**Comment by padvincenzo** [comment]
Hi @danmarsden , these problems should be now fixed with PR #29, can you run another test to confirm please?

**Comment by danmarsden** [comment]
Looks like 3 and 4 are sorted, but 1 and 2 still an issue - probably related to Php: 8.1 I'd guess.

It's occurring on this line:
https://github.com/Neuronys/moodle-local_nolej/blob/main/classes/api.php#L79

I'd guess "SYSCONTEXTID" is somehow returning the integer inside a string from Moodle core somewhere  - eg "3" instead of 3

this shouldn't block plugins db approval though.

**Comment by danmarsden** [comment]
changing: 
protected int $contextid = SYSCONTEXTID;

to:
protected $contextid = SYSCONTEXTID;

seems to fix it.

**Comment by padvincenzo** [comment]
Thanks @danmarsden , I've now updated the plugin.

**Comment by danmarsden** [comment]
cool thanks! - that cleared it :-)
